---
- name: Create partitions on /dev/sdc
  parted:
    device: /dev/sdc
    number: 1
    state: present
    part_type: primary
    fs_type: xfs
    part_start: 0%
    part_end: 40%

- name: Create second partition on /dev/sdc
  parted:
    device: /dev/sdc
    number: 2
    state: present
    part_type: primary
    fs_type: ext4
    part_start: 40%
    part_end: 100%

- name: Format /dev/sdc1 as xfs
  filesystem:
    fstype: xfs
    dev: /dev/sdc1

- name: Format /dev/sdc2 as ext4
  filesystem:
    fstype: ext4
    dev: /dev/sdc2

- name: Create /part1 directory
  file:
    path: /part1
    state: directory

- name: Mount /part1
  mount:
    path: /part1
    src: /dev/sdc1
    fstype: xfs
    state: mounted

- name: Create /part2 directory
  file:
    path: /part2
    state: directory

- name: Mount /part2
  mount:
    path: /part2
    src: /dev/sdc2
    fstype: ext4
    state: mounted
