---
- name: Create group cloudadmins
  group:
    name: cloudadmins
    state: present

- name: Create users and assign to groups
  user:
    name: "{{ item }}"
    groups: "cloudadmins,wheel"
    shell: /bin/bash
    create_home: yes
    state: present
  loop:
    - user100
    - user200
    - user300

- name: Generate SSH key pair for users
  user:
    name: "{{ item }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  loop:
    - user100
    - user200
    - user300
